### ISSUE TITLE
Update minimist to latest

### ISSUE THREAD

**Issue by hkuchibhotla** [maxogden/simplify-geojson#13]
This repo uses `minmist 0.0.7,` which seems to have some security vulnerabilities. 
Can we update to the latest 1.2.5
```
   "minimist": "1.2.5"
```

Tests Passed

**Comment by ungoldman** [comment]
fine by me, PR welcome

**Comment by hkuchibhotla** [comment]
Thank you, can i get write access to commit/ open a PR?

**Comment by ungoldman** [comment]
@hkuchibhotla that's not generally how PRs work on github, you can fork and open a PR by following these instructions. https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

**Comment by hkuchibhotla** [comment]
Thank you @ungoldman, here it is: https://github.com/maxogden/simplify-geojson/pull/14

**Comment by ungoldman** [comment]
Thank you! Resolved in #14, published in [`v1.0.4`](https://github.com/maxogden/simplify-geojson/releases/tag/v1.0.4)
